title: Hao
description: > # this means to ignore newlines until "baseurl:"
   Coding, Woodworking, Exploring
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liuhao.im" # the base hostname & protocol for your site
intro: "Hi, I am Hao (👋): a coder, a woodworker, a blogger, and a father."

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  auto_id_prefix: 'id-'
