# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hao Liu
email: liuhao1990@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   An artisan in the digital age
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liuhao.im" # the base hostname & protocol for your site
twitter_username: dabin
github_username:  fuermosi777

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
